import { Validators } from '@angular/forms';

export const globalConstans = {
  customerFormConfig: [
    {
      name: 'userId',
      initialValue: 0,
      width: 'col-',
      label: '',
      isHidden: true,
      placeholder: '',
      type: 'number',
      option: [],
      validatorFun: [],
    },
    {
      name: 'userName',
      initialValue: '',
      width: 'col-12',
      label: 'User Name',
      isHidden: false,
      placeholder: 'User Name',
      type: 'text',
      option: [],
      validatorFun: [Validators.required, Validators.minLength(3)],
    },
    {
      name: 'emailId',
      initialValue: '',
      width: 'col-12',
      label: 'Email Id',
      isHidden: false,
      placeholder: 'Email-id',
      type: 'email',
      option: [],
      validatorFun: [Validators.required, Validators.email],
    },
    {
      name: 'password',
      initialValue: '',
      width: 'col-6',
      label: 'Password',
      isHidden: false,
      placeholder: 'Enter Password',
      type: 'password',
      option: [],
      validatorFun: [Validators.required, Validators.minLength(6)],
    },
    {
      name: 'state',
      initialValue: '',
      width: 'col-6',
      label: 'Select State',
      isHidden: false,
      placeholder: 'Select State',
      type: 'select',
      option: ['Maharastra', 'Karnataka', 'Goa'] ,
      validatorFun: [Validators.required],
    },
    {
      name: 'city',
      initialValue: '',
      width: 'col-6',
      label: 'Select City',
      isHidden: false,
      placeholder: 'Select City',
      type: 'select',
      option: ['Pune', 'Nagpur', 'Mumbai'],
      validatorFun: [Validators.required],
    },
    {
      name: 'address',
      initialValue: '',
      width: 'col-12',
      label: 'Address',
      isHidden: false,
      placeholder: 'Enter Address',
      type: 'textarea',
      option: [],
      validatorFun: [],
    },
    {
      name: 'isActive',
      initialValue: false,
      width: 'col-4',
      label: 'Select Status',
      isHidden: false,
      placeholder: '',
      type: 'checkbox',
      option: [],
      validatorFun: [],
    },
  ],
};

// {
//   "userId": 0,
//   "userName": "string",
//   "emailId": "string",
//   "fullName": "string",
//   "password": "string"
// }
